### PR TITLE
#35 support relay modern template literals

### LINKED ISSUE #35: Support Relay modern template strings
Currently syntax highlighting is supported for Relay classic template strings.

```js
gql`
query {
  field
}
`

Relay.QL`
query {
  field
}
`
```

But not Relay modern template strings.

```js
graphql`
query {
  field
}
`
```

It would be great to update this!

### PR DESCRIPTION
**Pull request by ajhyndman**
Fixes #35

### CODE REVIEW

**Comment by kumarharsh** [comment]
Thank you @ajhyndman.

**Comment by ajhyndman** [comment]
@kumarharsh Any chance of a release soon-ish as well?  😄 

I have some colleagues I'm trying to sell on your extension!

**Comment by kumarharsh** [comment]
Will be doing it tomorrow for sure ☺

**Comment by kumarharsh** [comment]
Commit merged manually - ebfbce3f176

**Comment by kumarharsh** [comment]
Also, please note that for the plugin to work, you'll need to modify your `.gqlconfig` file to replace `Relay.QL` in the parser to be `graphql`.

```js
{
  ...
  query: {
     files: [
       {
         match: 'ui/src/**/*.js',
         parser: ['EmbeddedQueryParser', { startTag: 'graphql`', endTag: '`' }],
  ...
```

**Pull request closed without merging**
