### PR TITLE
Support more syntax highlighting triggers

### PR DESCRIPTION
**Pull request by kachkaev**
Inspired by Atom language-babel package:
https://github.com/gandm/language-babel/blob/f1bcd82d1f0f8f151b64daf331fb017ce6540c72/grammars/Babel%20Language.json#L1112

Closes https://github.com/kumarharsh/graphql-for-vscode/issues/69

### CODE REVIEW

**Comment by cjhowe7** [comment]
I wonder if this regex would work, which would be a more minimal change:
```js
"(Relay\\.QL|gql|graphql(\\.experimental)?|/\\* GraphQL \\*/)\\s*(`)"
```

**Comment by kachkaev** [comment]
Let's see what @kumarharsh suggests. I also thought of making RegExp shorted but then leaned towards keeping the regexps in both extensions in sync. Makes future updates easier.

**Comment by kumarharsh** [comment]
Thanks @kachkaev. That regex looks a little too complicated so i'll verify on my end if we really need the extra stuff there before merging this PR. 👍🏼

**Comment by kumarharsh** [comment]
This has been merged in master in 91917f0

**Pull request closed without merging**
