### PR TITLE
Allow for .graphqls files

### PR DESCRIPTION
**Pull request by kamilkisiela**

### CODE REVIEW

**Comment by kumarharsh** [comment]
Whats a graphqls file?

**Comment by Urigo** [comment]
@kumarharsh it's a file extension for GraphQL Schemas. WebStorm uses that to distinguish between a schema file and queries

**Comment by Urigo** [comment]
https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/search?utf8=%E2%9C%93&q=graphqls&type=

**Comment by kumarharsh** [comment]
Thanks, didn't know that!

**Pull request merged**
